import type { Metadata } from "next";
import "react-international-phone/style.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import AntDesignProvider from "@/components/providers/AntDesignProvider";
import QueryProvider from "@/components/providers/query-provider";
import { Sora } from "next/font/google";
import "./globals.css";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sora.variable} h-full antialiased`}
    >
      <body className={`${sora.className} flex min-h-full flex-col`}>
        <AntdRegistry>
          <AntDesignProvider>
              <QueryProvider>
               {children}
             </QueryProvider>
          </AntDesignProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
